export const ApiUrl = {
  login: 'Admin/Login',
  list_group_owner: 'Admin/list_group_owner',
  managed_group_owner: 'Admin/managed_group_owner',
  add_edit_group_owner: 'Admin/add_edit_group_owner',
  managed_peroperties: 'Admin/managed_peroperties',
  list_properties: 'Admin/list_properties',
  add_edit_peroperties: 'Admin/add_edit_peroperties',
  resetPassword: 'user/resetPassword',
  list_agents: 'Admin/list_agents',
  getResetPasswordToken: 'user/getResetPasswordToken',
  manage_plans: 'Admin/manage_plans',
  upload_api: 'OpenApi/file_upload',
  managed_peroperty_categories: 'Admin/managed_peroperty_categories',
  list_banners: 'Admin/list_banners',
  managed_peroperty_address: 'Admin/managed_peroperty_address',
  list_peroperty_categories: 'Admin/list_peroperty_categories',
  add_edit_peroperty_categories: 'Admin/add_edit_peroperty_categories',
  add_edit_banners: 'Admin/add_edit_banners',
  delete_banners: 'Admin/delete_banners',
  managed_agents: 'Admin/managed_agents',
  list_members: 'Admin/list_members',
  list_customer_request: 'Admin/list_customer_request',
  managed_members: 'Admin/managed_members',
  list_property_address: 'Admin/list_property_address',
  add_edit_agents: 'Admin/add_edit_agents',
  add_edit_peroperty_address: 'Admin/add_edit_peroperty_address'

};
