export const ApiUrl = {
  login: 'Admin/Login',
  list_group_owner: 'Admin/list_group_owner',
  managed_group_owner: 'Admin/managed_group_owner',
  add_edit_group_owner: 'Admin/add_edit_group_owner',

  getResetPasswordToken: 'user/getResetPasswordToken',

  verifyTwoFactorAuth: 'user/verifyTwoFactorAuth',
  resendTwoFactorAuth: 'user/resendTwoFactorAuth',
  resetPassword: 'user/resetPassword',
  logout: 'user/logout',
  sendHelpMessage: 'serviceProvider/sendHelpMessage',
  corporateGetBookingsCopy: 'corporate/getBookingsCopy',
  hospitalGetBookingsCopy: 'hospital/getBookingsCopy',
  hospitalGetTabsCountData: 'hospital/getTabsCountData',
  corporateGetTabsCountData: 'corporate/getTabsCountData',
  getCreatorAndSpList: 'hospital/getCreatorAndSpList',

  list_vendor: 'Admin/list_vendor',
  add_edit_plans: 'Admin/add_edit_plans',
  list_plans: 'Admin/list_plans',
  manage_plans: 'Admin/manage_plans',
  add_edit_vendor: 'Admin/add_edit_vendor',
  list_business_category: 'Admin/list_business_category',
  edit_keys: 'Admin/edit_keys',
  add_edit_business_category: 'Admin/add_edit_business_category',
  check_vendor_profile: 'Admin/check_vendor_profile',
  edit_vendor_permission: 'Admin/edit_vendor_permission',
  list_vendor_permissions_profile: 'Admin/list_vendor_permissions_profile',
  upload_api: 'OpenApi/file_upload',
  list_categories: 'Admin/list_categories',
  add_edit_categories: 'Admin/add_edit_categories',
  list_services: 'Admin/list_services',
  sugestions_lags_list: 'Admin/sugestions_lags_list',
  list_banners: 'Admin/list_banners',
  list_content: 'Admin/list_content',
  add_edit_services: 'Admin/add_edit_services',
  delete_block_users: 'Admin/delete_block_users',
  add_edit_banners: 'Admin/add_edit_banners',
  upload_content: 'Admin/upload_content',
  delete_banners: 'Admin/delete_banners',
  delete_block_vendor: 'Admin/delete_block_vendor',
  list_users_address: 'Admin/list_users_address',
  add_edit_tutorials: 'Admin/add_edit_tutorials',
  list_tutorials: 'Admin/list_tutorials',
  check_domain: 'Admin/check_domain',
  list_users: 'Admin/list_users',
  list_appointment: 'Admin/list_appointment',
  list_keys: 'Admin/list_keys',
  list_currency: 'Admin/list_currency',
  list_languages: 'Admin/list_languages',
  dashboard: 'api/Dashboard/Count',
  categories: 'api/Category',
  deleteData: 'api/Delete',
  blockData: 'api/Block',
  access_token_login: 'Admin/access_token_login'
};
